name: FPGA Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t fpga-pipeline .

      - name: Upload bitstream artifact
        uses: actions/upload-artifact@v3
        with:
          name: rca_bitstream
          path: bitstreams/*.sof
